from environments.multiagent.cars import CarConfig, EnginePower, TyreType

OBS_FRAME_STACK = 4
NORMALIZE_REWARDS = True
NUM_ENV_RUNNERS = 4
ROLLOUT_FRAGMENT_LENGTH = 400
TRAIN_MAX_TIMESTEPS = 500
TRAIN_GAMMA = 0.98
TRAIN_NUM_ITERATIONS = 3000
MINI_BATCH_SIZE = 64
TRAIN_CLIP_PARAM = 0.2
TRAIN_NUM_EPOCHS = 5
LR_SCHEDULE_START = 0.0001
LR_SCHEDULE_END = 0.000001
EVAL_INTERVAL = 50
EVAL_MAX_TIMESTEPS = 700
EVAL_DURATION = 3
NUM_CARS = 4
CAR_CONFIGS = [
    CarConfig(EnginePower.MEDIUM, TyreType.MEDIUM),
    CarConfig(EnginePower.MEDIUM, TyreType.MEDIUM),
    CarConfig(EnginePower.MEDIUM, TyreType.MEDIUM),
    CarConfig(EnginePower.MEDIUM, TyreType.MEDIUM),
]
